name: Lint
run-name: Lint new code on branch ${{ github.ref }}
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm i
      - name: Lint everything
        run: npm run lint
