name: Lint
run-name: Lint new code on branch ${{ github.ref }}
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        uses: npm i
      - name: Execute TSC
        run: npx tsc --noEmit
      - name: Execute ESLint
        run: npx eslint --fix .
      - name: Execute Prettier
        run: npx prettier --write .
