name: Release
run-name: Release
on:
  pull_request:
    branch: dev
    types: [closed]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm i
      - name: WiP tests
        run: echo "We should launch tests here"
  Release:
    runs-on: ubuntu-latest
    needs: Test
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm i
      - name: Release
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          npm run release
          git push
          echo "Success!"
