name: Run Tests [WiP]
run-name: Run Tests [WiP]
on: pull_request
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm i
      - name: WiP log
        run: echo "We should launch tests here"
